### ISSUE TITLE
Driver para Barômetro

### ISSUE THREAD

**Issue by leocelente** [zenitheesc/Drivers#33]
# Aplicação: Barômetro

O responsável por esse issue deve: 
 - **Pesquisar sobre essa aplicação**
    - Em qual contexto do projeto será utilizada? 
    - Qual geralmente é o propósito dessa aplicação? 
    - Existe algum dispositivo comum?
 - **Pesquisar sobre o dispositivo atual**
    - Por que estamos usando ele?
    - Tem algo que torna ele difícil de trabalhar?
    - Onde ele já foi utilizado?
 - **Implementar uma biblioteca do dispositivo.**
    - Qual informação está associada ao dispositivo?
    - Como se espera que ele seja utilizado?
    - Sua implementação compila sem Warnings?
 - **Documentar a Implementação**
    - O que cada função faz?
    - O que cada struct e seus campos significam?
    - Quais características do dispositivo afetam o código?
    - Quais partes do datasheet um usuário do driver deve ficar atento?
    - Existe alguma outra documentação externa de interesse para o usuário?

## Tarefas
- [x] Pesquisa e Leitura do Datasheet
- [x] Selecionar Features
- [x] Rascunho da Interface
- [x] Implementação
- [ ] Documentação
- [ ] Revisão 
- [ ] Teste
- [ ] Finalização

**Comment by GustavoKanaiama** [comment]
Jóia

**Comment by leocelente** [comment]
:gem:

**Comment by leocelente** [comment]
#31 foi um teste
