### ISSUE TITLE
Error: Platform e arduino esp32

### ISSUE THREAD

**Issue by Murilotrevisan** [zenitheesc/Drivers#43]
Platform não funciona com esp32 no arduino IDE
Conflito de nomes da platform com a HAL da ESP32

**Comment by leocelente** [comment]
Em resumo a Espressif utilizou identificadores para as principais `typedef struct` dos protcolos, I2C, SPI, UART etc como `i2c_t`, sem muitas qualificações. Como o objetivo da platform é simplificar o código e ser a ultima (top most) camada de abstração também escolhemos esses nomes. Esse conflito de nomes impede a compilação. Como solução "temporária" foram adicionadas macros para renomear nossos `typedefs` para diferenciá-los dentro dos arquivos do projeto (`main.c` etc)  e dentro do `platform.h`.
